### ISSUE TITLE
performance regression with nested quantifiers in v11

### ISSUE THREAD

**Issue by brawlin2** [LeventErkok/sbv#733]
I'm seeing a performance regression in v11 vs. v10, demonstrated by the following program.
```
{-# LANGUAGE ScopedTypeVariables #-}

import Data.SBV

wrapForalls :: Integer -> SBool -> SBool
wrapForalls n term = if n <= 0
                     then term
                     else wrapForalls (n - 1) (wrapForall term)
  where
    wrapForall :: SBool -> SBool
    wrapForall t = quantifiedBool (\ (Forall (_ :: SBool)) -> t)

main :: IO ()
main = do
  let n = 13 -- SBV v11 scales badly as this increases; SBV v10 seems fine
  s <- generateSMTBenchmarkSat (wrapForalls n sTrue)
  _ <- putStr s
  return ()
```

In v11:
- **(the main issue)** Increasing `n` in `main` leads to runaway memory (and time) usage when generating the SMT-LIB encoding; at `n = 13`, it's already up to several gigabytes allocated and several seconds to execute.
- The `forall`s are interspersed with (trivial) `let`s.

In v10: 
- The performance is as expected: fast, with little memory usage.
- There are no `let`s in the output.

The `forall`/`let` structure obviously doesn't explain the performance difference in and of itself, but perhaps it's related?

**Comment by LeventErkok** [comment]
Lots of things changed with regards to quantifiers in the last couple of versions; I'm not surprised that performance got impacted.

Is there any way you can do some profiling and identify where the culprit might be. That'd be most helpful in identifying the root cause.

**Comment by brawlin2** [comment]
Yeah, I noticed the API changes around quantifiers when moving from v8 to v10; it all seems to have improved significantly, so thanks for that!

I profiled via `+RTS -p -hT`, and the outputs are attached (with some `.txt` extensions added, for GitHub I guess?).  Here's the beginning of the `.prof` output:
```
	Fri Feb 14 08:03 2025 Time and Allocation Profiling Report  (Final)

	   experiment +RTS -p -hT -RTS

	total time  =        3.64 secs   (3639 ticks @ 1000 us, 1 processor)
	total alloc = 9,222,965,120 bytes  (excludes profiling overheads)

COST CENTRE          MODULE                               SRC                                                        %time %alloc

uniplateData         Data.Generics.Uniplate.Internal.Data Data/Generics/Uniplate/Internal/Data.hs:(250,1)-(257,36)    33.3   36.6
uniplateData.combine Data.Generics.Uniplate.Internal.Data Data/Generics/Uniplate/Internal/Data.hs:(253,9)-(254,90)    19.6   40.0
biplate.answer       Data.Generics.Uniplate.Data          Data/Generics/Uniplate/Internal/DataInc.hs:16:15-64          7.7    4.8
biplateData          Data.Generics.Uniplate.Internal.Data Data/Generics/Uniplate/Internal/Data.hs:(243,1)-(246,27)     5.9    0.0
compare              Data.SBV.Core.Symbolic               Data/SBV/Core/Symbolic.hs:258:23-25                          4.5    0.0
biplate              Data.Generics.Uniplate.Data          Data/Generics/Uniplate/Internal/DataInc.hs:(15,5)-(16,64)    3.4    0.0
cvt.hasOverflows     Data.SBV.SMT.SMTLib2                 Data/SBV/SMT/SMTLib2.hs:66:9-81                              3.2    2.4
cvt.hasRegExp        Data.SBV.SMT.SMTLib2                 Data/SBV/SMT/SMTLib2.hs:59:9-84                              3.1    2.4
cvt.hasFoldMap       Data.SBV.SMT.SMTLib2                 Data/SBV/SMT/SMTLib2.hs:(76,9)-(81,97)                       3.1    2.4
convert              Data.SBV.Lambda                      Data/SBV/Lambda.hs:(197,1)-(201,64)                          3.1    2.4
runSymbolicInState   Data.SBV.Core.Symbolic               Data/SBV/Core/Symbolic.hs:(1916,1)-(1930,18)                 3.0    2.4
uniplate.answer      Data.Generics.Uniplate.Data          Data/Generics/Uniplate/Internal/DataInc.hs:6:15-64           2.7    1.9
fromOracle           Data.Generics.Uniplate.Internal.Data Data/Generics/Uniplate/Internal/Data.hs:59:26-35             1.9    0.0
==                   Data.SBV.Core.Symbolic               Data/SBV/Core/Symbolic.hs:258:19-20                          1.5    0.0
toLambda.sh.res      Data.SBV.Lambda                      Data/SBV/Lambda.hs:(264,16)-(267,30)                         1.4    2.4
cvt.funcMap.revs     Data.SBV.SMT.SMTLib2                 Data/SBV/SMT/SMTLib2.hs:294:17-89                            1.4    2.4
uniplate             Data.Generics.Uniplate.Data          Data/Generics/Uniplate/Internal/DataInc.hs:(5,5)-(6,64)      1.1    0.0
```

[experiment.hp.txt](https://github.com/user-attachments/files/18802270/experiment.hp.txt)
[experiment.pdf](https://github.com/user-attachments/files/18802269/experiment.pdf)
[experiment.prof.txt](https://github.com/user-attachments/files/18802271/experiment.prof.txt)

**Comment by LeventErkok** [comment]
Thanks for the analysis. I'm not surprised to see uniplate in there, as we perform a lot of walks over the internal structure to handle-lambdas and quantifiers. It's really tricky to get to the bottom of these, but I'll surely take a look.

@doyougnu Hi Jeffrey: Performance is your expertise area. Do you have any cycles to take a look at this and perhaps suggest some changes?

**Comment by doyougnu** [comment]
Sure I can take a stab at it. The profile suggests this is almost all uniplate, the call stack is here (notice the ~40% inherited column):

```
    runSymbolic                                                  Data.SBV.Core.Symbolic                 Data/SBV/Core/Symbolic.hs:(1890,1)-(1892,29)              15972           1    0.0    0.0    46.2   42.9
     runSymbolicInState                                          Data.SBV.Core.Symbolic                 Data/SBV/Core/Symbolic.hs:(1916,1)-(1930,18)              16041          14    3.0    2.4    46.2   42.9
...
      runSymbolicInState.check                                   Data.SBV.Core.Symbolic                 Data/SBV/Core/Symbolic.hs:(1923,8)-(1926,75)              16482           1    0.0    0.0     0.0    0.0
       sbvContext                                                Data.SBV.Core.Symbolic                 Data/SBV/Core/Symbolic.hs:1191:23-32                      16483           1    0.0    0.0     0.0    0.0
      >>=                                                        Data.SBV.Core.Symbolic                 Data/SBV/Core/Symbolic.hs:1628:61-65                      16067           0    0.0    0.0    20.9   16.7
       output                                                    Data.SBV.Core.Data                     Data/SBV/Core/Data.hs:(566,3)-(568,18)                    16072          14    0.0    0.0    20.9   16.7
        outputSVal                                               Data.SBV.Core.Symbolic                 Data/SBV/Core/Symbolic.hs:(2071,1)-(2078,49)              16081          14    0.0    0.0     0.0    0.0
        unSBV                                                    Data.SBV.Core.Data                     Data/SBV/Core/Data.hs:115:23-27                           16075          14    0.0    0.0     0.0    0.0
        >>                                                       Data.SBV.Core.Symbolic                 Data/SBV/Core/Symbolic.hs:1628:61-65                      16074           0    0.0    0.0    20.9   16.7
         outputSVal                                              Data.SBV.Core.Symbolic                 Data/SBV/Core/Symbolic.hs:(2071,1)-(2078,49)              16083           0    0.0    0.0    20.9   16.7
...
...
      biplate                                                    Data.Generics.Uniplate.Data            Data/Generics/Uniplate/Internal/DataInc.hs:(15,5)-(16,64) 16256           0    1.3    0.0    22.3   23.8
       biplateData                                               Data.Generics.Uniplate.Internal.Data   Data/Generics/Uniplate/Internal/Data.hs:(243,1)-(246,27)  16257    10965551    1.3    0.0    17.3   21.9
        uniplateData                                             Data.Generics.Uniplate.Internal.Data   Data/Generics/Uniplate/Internal/Data.hs:(250,1)-(257,36)  16420    10965455   10.2   10.5    16.0   21.9
         fromC                                                   Data.Generics.Uniplate.Internal.Data   Data/Generics/Uniplate/Internal/Data.hs:237:20-24         16421    10965455    0.0    0.0     0.0    0.0
         uniplateData.create                                     Data.Generics.Uniplate.Internal.Data   Data/Generics/Uniplate/Internal/Data.hs:257:9-36          16430    10956699    0.0    0.0     0.0    0.0
         uniplateData.combine                                    Data.Generics.Uniplate.Internal.Data   Data/Generics/Uniplate/Internal/Data.hs:(253,9)-(254,90)  16431    10948381    5.8   11.4     5.8   11.4
          gfoldl                                                 Data.SBV.Core.Symbolic                 Data/SBV/Core/Symbolic.hs:258:37-42                       16775           0    0.0    0.0     0.0    0.0
          gfoldl                                                 Data.SBV.Core.Symbolic                 Data/SBV/Core/Symbolic.hs:720:25-30                       16695           0    0.0    0.0     0.0    0.0
          gfoldl                                                 Data.SBV.Core.Symbolic                 Data/SBV/Core/Symbolic.hs:727:43-48                       16455           0    0.0    0.0     0.0    0.0
          gfoldl                                                 Data.SBV.Core.Symbolic                 Data/SBV/Core/Symbolic.hs:143:18-23                       16454           0    0.0    0.0     0.0    0.0
          gfoldl                                                 Data.SBV.Core.Symbolic                 Data/SBV/Core/Symbolic.hs:855:25-30                       16440           0    0.0    0.0     0.0    0.0
          gfoldl                                                 Data.SBV.Core.Symbolic                 Data/SBV/Core/Symbolic.hs:890:31-36                       16432           0    0.0    0.0     0.0    0.0
         gfoldl                                                  Data.SBV.Core.Symbolic                 Data/SBV/Core/Symbolic.hs:258:37-42                       16699        8191    0.0    0.0     0.0    0.0
```

which I think corresponds to [this line](https://github.com/LeventErkok/sbv/blob/4c81e9ccc34e14e9aad22f86c9848d057b5b7fda/Data/SBV/Core/Symbolic.hs#L1980).

The heap profile suggests that this traversal is building up thunks that then get immediately consumed (we see the classic pyramid shape repeated several times in the profile).

The `gfoldl` is consipicuous to me. I think that is the root cause by building up thunks between constructor fields and then `nub` is forcing these thunks, normally I would suggest using `gfoldl'` or a strict application function but this is an internal call in uniplate.

 Its not surprising to me that that is exponential since [nub](https://hackage.haskell.org/package/base-4.21.0.0/docs/Data-List.html#v:nub) is O(n^{2}). Removing that call to `nub` should do a lot to solve the regression. The data that is being `nub`'d is ordinal? If so then there is another `nub` in [containers](https://hackage.haskell.org/package/containers-0.7/docs/Data-Containers-ListUtils.html#v:nubOrd) that has better complexity. 

Other than that are you using `Data.Generics.Uniplate.Direct`? The docs say that is the more performant module, so I bet that would issue a call to `gfoldl'` and would be a good first test.

**Comment by LeventErkok** [comment]
Thanks for the analysis Jeff. I think trying to get rid of `nub` (or replacing it with `nubOrd`) is a good idea. I think the only reason we call `nub` there is to reduce the amount of work the checker will have to do. Funny it ends up costing more.

I'll take a stab at this soon to see if things can be improved. Much appreciated.

**Comment by LeventErkok** [comment]
@brawlin2 

I've committed https://github.com/LeventErkok/sbv/commit/deab79e1e76187bc2c755bfe4c8a32833a8dda8b which should be more performant for the example you've sent.

Construction of nested-lambdas are inherently expensive; so there might be other optimization opportunities here. Can you give this a try on your actual use case (I assume the program you sent above isn't really what you care about!), and see if it performs sufficiently for the actual use case?

**Comment by brawlin2** [comment]
@LeventErkok Thanks for the update.  It's much better, but not a complete fix: in my real program it's gone from catastrophic memory consumption to more like a 10x slowdown (along with significant --- but not "catastrophic" --- memory consumption) with SBV v11 plus the patch vs. v10.

Here's some fresh profiling output, **after changing `let n = 13` to `let n = 42` in the test program** (now that it can handle a little more).

# v11 at commit deab79e1e76187bc2c755bfe4c8a32833a8dda8b (along with Stackage LTS 23.8)
```
	Thu Feb 20 09:21 2025 Time and Allocation Profiling Report  (Final)

	   experiment +RTS -p -hT -RTS

	total time  =        4.17 secs   (4174 ticks @ 1000 us, 1 processor)
	total alloc = 7,971,674,552 bytes  (excludes profiling overheads)

COST CENTRE          MODULE                               SRC                                                        %time %alloc

uniplateData         Data.Generics.Uniplate.Internal.Data Data/Generics/Uniplate/Internal/Data.hs:(250,1)-(257,36)    38.1   36.0
convert              Data.SBV.Lambda                      Data/SBV/Lambda.hs:(247,1)-(251,64)                         19.1   12.9
uniplateData.combine Data.Generics.Uniplate.Internal.Data Data/Generics/Uniplate/Internal/Data.hs:(253,9)-(254,90)    18.8   39.2
biplate.answer       Data.Generics.Uniplate.Data          Data/Generics/Uniplate/Internal/DataInc.hs:16:15-64          8.2    6.5
biplateData          Data.Generics.Uniplate.Internal.Data Data/Generics/Uniplate/Internal/Data.hs:(243,1)-(246,27)     4.3    0.0
biplate              Data.Generics.Uniplate.Data          Data/Generics/Uniplate/Internal/DataInc.hs:(15,5)-(16,64)    3.4    0.0
runSymbolicInState   Data.SBV.Core.Symbolic               Data/SBV/Core/Symbolic.hs:(1968,1)-(1982,18)                 1.7    0.9
fromOracle           Data.Generics.Uniplate.Internal.Data Data/Generics/Uniplate/Internal/Data.hs:59:26-35             1.5    0.0
cvt.hasLambdas       Data.SBV.SMT.SMTLib2                 Data/SBV/SMT/SMTLib2.hs:(105,9)-(113,99)                     1.4    0.9
cvt.hasRegExp        Data.SBV.SMT.SMTLib2                 Data/SBV/SMT/SMTLib2.hs:88:9-84                              1.2    0.9
```

[experiment.hp](https://github.com/user-attachments/files/18892322/experiment.hp.txt)
[experiment.log](https://github.com/user-attachments/files/18892319/experiment.log)
[experiment.pdf](https://github.com/user-attachments/files/18892321/experiment.pdf)
[experiment.prof](https://github.com/user-attachments/files/18892320/experiment.prof.txt)

# v10.2 (Stackage LTS 22.43)
```
	Thu Feb 20 09:27 2025 Time and Allocation Profiling Report  (Final)

	   experiment +RTS -p -hT -RTS

	total time  =        0.01 secs   (6 ticks @ 1000 us, 1 processor)
	total alloc =   6,032,968 bytes  (excludes profiling overheads)

COST CENTRE                   MODULE                               SRC                                                       %time %alloc

MAIN                          MAIN                                 <built-in>                                                 16.7    0.0
uniplateData                  Data.Generics.Uniplate.Internal.Data Data/Generics/Uniplate/Internal/Data.hs:(250,1)-(257,36)   16.7   13.2
generateSMTBenchMarkGen       Data.SBV.Provers.Prover              Data/SBV/Provers/Prover.hs:(572,1)-(583,39)                16.7    1.7
findTupleArities              Data.SBV.SMT.SMTLib2                 Data/SBV/SMT/SMTLib2.hs:(378,1)-(380,76)                   16.7    0.0
constraintGen.mkDef.\         Data.SBV.Lambda                      Data/SBV/Lambda.hs:(162,66)-(164,94)                       16.7   23.8
show                          Data.SBV.Core.Symbolic               Data/SBV/Core/Symbolic.hs:2066:3-47                        16.7    2.1
uniplateData.combine          Data.Generics.Uniplate.Internal.Data Data/Generics/Uniplate/Internal/Data.hs:(253,9)-(254,90)    0.0   14.5
biplate.answer                Data.Generics.Uniplate.Data          Data/Generics/Uniplate/Internal/DataInc.hs:16:15-64         0.0    1.8
defineFun                     Data.SBV.SMT.SMTLib2                 Data/SBV/SMT/SMTLib2.hs:(527,1)-(536,65)                    0.0    1.1
cvt.hasRegExp                 Data.SBV.SMT.SMTLib2                 Data/SBV/SMT/SMTLib2.hs:58:9-84                             0.0    1.2
cvt.hasOverflows              Data.SBV.SMT.SMTLib2                 Data/SBV/SMT/SMTLib2.hs:68:9-81                             0.0    1.2
cvt.hasFoldMap                Data.SBV.SMT.SMTLib2                 Data/SBV/SMT/SMTLib2.hs:(77,9)-(82,97)                      0.0    1.2
cvt.funcMap.reverses          Data.SBV.SMT.SMTLib2                 Data/SBV/SMT/SMTLib2.hs:(299,17)-(300,77)                   0.0    1.2
toLambda.sh.res               Data.SBV.Lambda                      Data/SBV/Lambda.hs:(253,16)-(255,51)                        0.0   21.8
toLambda.sh.mbParam.paramList Data.SBV.Lambda                      Data/SBV/Lambda.hs:267:24-125                               0.0    1.1
constraintGen                 Data.SBV.Lambda                      Data/SBV/Lambda.hs:(157,1)-(168,99)                         0.0    1.3
```

[experiment.hp](https://github.com/user-attachments/files/18892377/experiment.hp.txt)
[experiment.log](https://github.com/user-attachments/files/18892379/experiment.log)
[experiment.pdf](https://github.com/user-attachments/files/18892380/experiment.pdf)
[experiment.prof](https://github.com/user-attachments/files/18892378/experiment.prof.txt)

**Comment by LeventErkok** [comment]
@doyougnu aptly observed the root cause here. The use of `Data.Generics.Uniplate.Data` is expensive. `Data.Generics.Uniplate.Direct` is a much better choice, alas it requires writing a lot of instances which is error-prone and honestly a lot of work to convert and maintain.

I'll see if I can simplify more cases for unicode cases, but this might be the cost of relying on uniplate. (It's an awesome library, but perhaps I'm relying on it a bit too much.)

**Comment by LeventErkok** [comment]
@brawlin2 OK; I pushed in a few more fixes that I believe should behave a bit better. Can you give it another try?

**Comment by brawlin2** [comment]
The newest change does indeed help some more, but now `let n = 99` is enough to demonstrate significant remaining slowness/memory usage.  Unfortunately, it's still the same major slowdown in my real program.  (Also, for whatever reason, I needed to add `foldl'` to the `Data.List` import list to get it to compile; maybe that's down to the Stackage LTS release that I'm using?)

I'm happy to keep reporting back on new patches if you have more ideas, and I can add some profiling data from this one if it's useful.  In case it helps, now that I'm set up to run from a local version of SBV, I did a `git bisect` and found 3f03db2c46f9c7523f4b243e64ffeabb927a3e1c to be the apparent culprit where the slowdown was introduced.  Does anything in that patch jump out at you?

**Comment by LeventErkok** [comment]
That commit was a bug fix. Before that, SBV forgot to generate code for functions such as `reverse`/`fold`/`any` etc., that appeared under a quantifier/lambda. I assume you don't actually use such functions, but you end up paying for a feature you don't need. (Essentially, SBV spits out monomorphic instances of such polymorphic functions, and thus needed to keep track of any usage under lambdas and quantifiers.)

The good news is that we won't need this facility once SMTLib 3.0 becomes the supported standard, which will allow polymorphic functions to be defined once and for all, just like in Haskell. The bad news is that SMTLib 3.0 is still quite a bit far ahead; I expect z3 and CVC5 to support it perhaps sometime in the next year.

The call `quantifiedBool` is inherently expensive. When you nest it like you do in your test, it becomes really expensive. I'm having hard time imagining what your actual use case is: Why do you need such deep levels of nesting? Can you "group" them together and declare all the parameters once? (That'd make it really cheaper.) That is, there's a big performance difference between:

```haskell
quantifiedBool (\(Forall x) -> quantifiedBool (\(Forall y) -> x .&& y))
````

and

```haskell
quantifiedBool (\(Forall x) (Forall y) -> x .&& y)
```

even though they're semantically equivalent. If you give me an idea about why you need such deep nestings, maybe I can come up with a different idea for you.

In the meantime, I'll take another look at if we can improve the existing code base to push it a bit further. But knowledge of your actual use case would help out in case this turns out to be an XY-problem.

**Comment by brawlin2** [comment]
> functions such as `reverse`/`fold`/`any` etc., that appeared under a quantifier/lambda. I assume you don't actually use such functions, but you end up paying for a feature you don't need. (Essentially, SBV spits out monomorphic instances of such polymorphic functions, and thus needed to keep track of any usage under lambdas and quantifiers.)

I see.  Thanks for the explanation, that makes sense!  You're correct that I'm not using any polymorphic functions; I have a pretty simple expression language with things like Booleans, numbers, [first-order] quantifiers, etc., that I do SMT queries over using SBV.  I was hoping to avoid something like prenex-normal-form conversion (or other special handling/grouping of quantifiers) and push that work into SBV if possible 😅, but I'll explore workarounds in the meantime.

As a starting point for figuring out how to come up with a workaround, do you have any quick suggestion (or info) on how to define a `wrapForalls'` function as in the example that doesn't use `quantifiedBool` internally, so that the line in `main` would become `s <- generateSMTBenchmarkSat (quantifiedBool (wrapForalls' n sTrue))`?  The call to `quantifiedBool` in `wrapForall` is a convenient way to get back to type `SBool`, rather than a lambda with some variable number/type of arguments.

**Comment by doyougnu** [comment]
> but I'll explore workarounds in the meantime.

Another option you might explore is to use z3's c library and GHC's FFI. You don't have to write this yourself there is a [z3 package](https://hackage.haskell.org/package/z3). Although I don't think its really maintained anymore (you can see a PR I opened that is still open in 2021 that has not been reviewed or commented on). 

The benefit of this is that the FFI will be much faster (100-1000x) than what sbv does (it opens a child process and writes through stdin/stdout buffers). That will only improve your performance if communicating with the solver is a very common thing you'll be doing. If you're just building up a single SMTLIB program and kicking off the work to the solver a few times (like under 100) than this won't make a material difference.

The downside is that its just a barebones api and so you'll have to make a lot of the conveniences that sbv provides by hand. You can use the code from my [phd work](https://github.com/doyougnu/VSmt/blob/f4200257c648f0d218006996088fb3023411dbf5/haskell/vsmt/Data/Solve.hs#L56) as an example. It should still work.

**Comment by LeventErkok** [comment]
I always encourage people to use different libraries. But so far as I understand the z3-package is no longer maintained. One thing I worry about is the maintenance of such packages that rely on FFI. These projects move quick, and things go stale. The advantage of sticking to SMTLib is that it's universal, and your solution can use z3/CVC5/Yices without having to maintain explicit APIs for all of these.

The other thing I observe is that API's using the FFI are extremely low-level; and while there's nothing stopping people from building much higher-level APIs like SBV supports on top of this, I don't think anybody has done it so far. I believe this is because it's really hard to maintain a very high-level API and also juggle FFI's of multiple solvers. Much easier when you stick to SMTLib.

If performance is a must, program straight in C/C++ for the solver of your choice. If you can't afford doing that, I actually think sticking to SMTLib pays off in the long run. Using low-level FFI based APIs are very hard to program with and maintain. But these things are necessarily subjective.

**Comment by doyougnu** [comment]
> These projects move quick, and things go stale. The advantage of sticking to SMTLib is that it's universal, and your solution can use z3/CVC5/Yices without having to maintain explicit APIs for all of these.

Yes I completely agree. For the record I think sbv makes very good tradeoffs in this area and really punches above its weight. 

> I believe this is because it's really hard to maintain a very high-level API and also juggle FFI's of multiple solvers. Much easier when you stick to SMTLib.

Yes and I think this is the exact reason why the z3-package is no longer maintained. My former Ph.D. advisor knows Iago, we asked him for support and he replied that the package was already very out of date and rotted (this was like 2020) and he didn't have the bandwidth to support it. Its simply too much work to track the changes for projects like z3. 

But I just wanted to offer it as an alternative. Its more work but its downsides might be reasonable for your use case. That was the case for me. I used sbv in my first prototype and then used the FFI bindings for my second and for my publications once I had the research nailed down. But for my use case I was interleaving my system with sat/smt calls so I wasn't solving one big smt problem, I was solving over 100k!

**Comment by brawlin2** [comment]
@LeventErkok @doyougnu Thanks for the suggestions and discussion, it's definitely apropos.

I have the "few big SMT queries" situation in this case (along with some lighter decision making based on the results to do things like running follow-up queries to explain results, etc.); SBV really shines there, with the ability to compare/try different solvers, etc.  With that in mind, I'm definitely going to stick to SBV, so a wave of the magic wand to make it as fast as it used to be when generating "simple" SMT-LIB would be great; I realize that's a lot to maintain when waiting for SMT-LIBv3 is the "right" solution, so I'll take a pass at making better use of `quantifiedBool` and report back.  The project where I'm using this is not open source (yet; stay tuned!), but I'll see whether I can carve out out some representative example code if I run into more trouble.

Incidentally, on a different project (https://github.com/sandialabs/mc3), I had the "many small queries" situation that @doyougnu describes, and to get better performance I eventually migrated away from Rosette (a Racket package that includes SMT-LIB-based solver interaction, like SBV) to calling Z3 via FFI.  (That migration hasn't been open sourced yet, so you won't see it in that linked repo.)

**Comment by LeventErkok** [comment]
@brawlin2 I just pushed in another set of changes, essentially avoiding the memory leak I hope. Can you give it another try and see if it performs better?

**Comment by LeventErkok** [comment]
@brawlin2 For your other question, i.e., regarding how you can avoid nesting quantifiers, this is one way to go about it:

```haskell
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE FlexibleContexts    #-}

{-# OPTIONS_GHC -Wall -Werror #-}

module T where

import Data.SBV
import Data.SBV.Internals(Constraint)

wrapForalls :: (Constraint Symbolic a, QuantifiedBool a) => Integer -> a -> SBool
wrapForalls 0 a = quantifiedBool a
wrapForalls n a = wrapForalls (n-1) (\(Forall (_ :: SBool)) -> a)

test :: IO ()
test = do
  let n = 13
  s <- generateSMTBenchmarkSat (wrapForalls n sTrue)
  putStr s
```

Note that we have to use the `Constraint` class that is not really exposed for the user, aside from the `Internals` module. I don't expect most people to use this sort of internal detail, but for this function it's needed.

When run, the above prints:

```
; Automatically created by SBV on 2025-02-21 11:02:50.375116 PST
(set-option :smtlib2_compliant true)
(set-option :diagnostic-output-channel "stdout")
(set-option :produce-models true)
(set-logic ALL) ; has quantified booleans, using catch-all.
; --- uninterpreted sorts ---
; --- tuples ---
; --- sums ---
; --- literal constants ---
; --- top level inputs ---
; --- constant tables ---
; --- non-constant tables ---
; --- uninterpreted constants ---
; --- user defined functions ---
; --- assignments ---
(define-fun s0 () Bool (forall ((l1_s0 Bool) (l1_s1 Bool) (l1_s2 Bool) (l1_s3 Bool) (l1_s4 Bool) (l1_s5 Bool) (l1_s6 Bool) (l1_s7 Bool) (l1_s8 Bool) (l1_s9 Bool) (l1_s10 Bool) (l1_s11 Bool) (l1_s12 Bool))
                          true))
; --- delayedEqualities ---
; --- formula ---
(assert s0)
(check-sat)
```

This should be preferred over deep nestings for performance reasons; though I believe the changes we put in place already should also handle nestings just fine.

Let me know what you find out..

**Comment by brawlin2** [comment]
> [@brawlin2](https://github.com/brawlin2) I just pushed in another set of changes, essentially avoiding the memory leak I hope. Can you give it another try and see if it performs better?

Success!  The test program now works fine for an excessive amount of nesting, `let n = 999`: about 2x the time/memory usage vs. v10, but that seems reasonable to me with the extra checks that were added --- no more obvious memory leak, and the profiling output looks "healthy".  My real program shows a similar response, so I'd call this issue resolved.

Also, thanks for the tip about the `Constraint` class.  I didn't find that in the past, which is probably part of how I ended up with the overuse of `quantifiedBool`.  I'll see what I can do with it and report back, but things are again working as expected for now.

Thanks again for working on this!  Here's some final profiling data, for completeness:

703e0f0898950e7f8efac6b29949414379604b36 (fixed):
[experiment.pdf](https://github.com/user-attachments/files/18915727/experiment.pdf)
[experiment.prof](https://github.com/user-attachments/files/18915728/experiment.prof.txt)

224b17675c5b19fab290bfeaa3ee952f26db907e (before the older bug fix that caused the performance regression):
[experiment.pdf](https://github.com/user-attachments/files/18915734/experiment.pdf)
[experiment.prof](https://github.com/user-attachments/files/18915737/experiment.prof.txt)

**Comment by LeventErkok** [comment]
Fantastic!

There'll be a new release of SBV shortly..  Glad these changes made it in.

**Comment by doyougnu** [comment]
@brawlin2 happy that you got to a resolution.
@LeventErkok excellent support as always 😄

**Comment by LeventErkok** [comment]
[SBV 11.1](https://hackage.haskell.org/package/sbv)  is now on Hackage. Enjoy!
